apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidal-casino-db
  labels:
    app: vidal-casino-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vidal-casino-db
  template:
    metadata:
      labels:
        app: vidal-casino-db
    spec:
      containers:
        - name: vidal-casino-db
          image: 631932931672.dkr.ecr.us-east-1.amazonaws.com/vidal-casino-db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: casino-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: casino-config
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: casino-config
                  key: DB_NAME
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: vidal-casino-db