name: Build & Deploy database

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths: [ 'db/**', '.github/workflows/deploy-db.yml' ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - id: ecr
        name: Autenticar en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build & push vidal-casino-db
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          IMAGE=$REGISTRY/vidal-casino-db
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest ./db
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
      - name: Actualizar Kubeconfig para Amazon EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name casino-eks

      - name: Desplegar Base de Datos en EKS con Kubectl
        run: |
          kubectl apply -f k8s/db-deployment.yaml

          kubectl rollout restart deployment/vidal-casino-db || true